#######################################
#                                     #
#           Survival Teams            #
#                                     #
#######################################

# Select the data storage (.txt files in local or in database)
# Valid values are 'file', 'mysql'
dataStorage: 'file'

# SQL Configuration
sqlCredentials:
  # The IP address of your host, ex: XXX.XX.XXX.XX
  host: 'yourhost'
  # The port to connect to the database, commonly 3306
  port: 'portofyourdb'
  # Username for the connexion
  user: 'username'
  # Password for the connexion
  password: 'password'
  # Name of the database
  dbName: 'dbname'
  # Prefix of the tables created by SurvivalTeams
  dbTablesPrefix: 'Teams'

# Language to use (from files)
lang: 'en-EN'

# Commands parameters
commands:
  # Whether to ask for confirmation on performing these commands
  # All the following apply only for the team leader
  confirmationOn:
    # memberInvite: true -> the player added by the team leader will be sent an invitation he can either accept or decline
    # memberInvite: false -> the player will be added by the team leader without asking
    memberInvite: true
    disband: true
    nameLeader: true
    quit: true
  # This is the maximum amount of teams that can be displayed with /st top
  # Reducing this number may optimize server performances
  # It must be greater than or equal to 1
  topMaxRank: 20o
  # This is the delay in seconds a player has in order to confirm commands that require confirmation
  # It must be a positive number
  confirmationDelay: 60

# The world in which teams can create their warp and players can teleport to
warpsWorld: "world"